# Generated by Django 5.0.7 on 2024-07-12 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('data', models.DateField()),
                ('telefone', models.CharField(max_length=15)),
                ('endereco', models.CharField(max_length=100)),
            ],
        ),
    ]
