# Generated by Django 5.0.7 on 2024-07-17 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_clientes_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='cep',
            field=models.CharField(default='00000000', max_length=8),
        ),
        migrations.AddField(
            model_name='clientes',
            name='cidade',
            field=models.CharField(default='SuaCidade', max_length=100),
        ),
        migrations.AddField(
            model_name='clientes',
            name='email',
            field=models.EmailField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
