# Generated by Django 5.0.7 on 2024-07-18 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_clientes_cep_clientes_cidade_clientes_email'),
        ('core', '0003_servicos'),
    ]

    operations = [
    ]
