# Generated by Django 5.0.7 on 2024-07-18 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_entradas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Saidas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('quantidade', models.IntegerField()),
                ('peca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pecas')),
            ],
        ),
    ]
