# Generated by Django 5.0.7 on 2024-07-18 23:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_saidas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientes',
            options={'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='entradas',
            options={'verbose_name': 'Entrada', 'verbose_name_plural': 'Entradas'},
        ),
        migrations.AlterModelOptions(
            name='pecas',
            options={'verbose_name': 'Peca', 'verbose_name_plural': 'Pecas'},
        ),
        migrations.AlterModelOptions(
            name='saidas',
            options={'verbose_name': 'Saida', 'verbose_name_plural': 'Saidas'},
        ),
        migrations.AlterModelOptions(
            name='servicos',
            options={'verbose_name': 'Servico', 'verbose_name_plural': 'Servicos'},
        ),
        migrations.CreateModel(
            name='Orcamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.clientes')),
            ],
            options={
                'verbose_name': 'Orçamento',
                'verbose_name_plural': 'Orçamentos',
            },
        ),
        migrations.CreateModel(
            name='OrcamentosPecas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_peca', models.CharField(max_length=100)),
                ('quantidade', models.IntegerField()),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.orcamentos')),
                ('peca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pecas')),
            ],
            options={
                'verbose_name': 'Orçamento Peça',
                'verbose_name_plural': 'Orçamentos Peças',
            },
        ),
        migrations.AddField(
            model_name='orcamentos',
            name='pecas',
            field=models.ManyToManyField(through='core.OrcamentosPecas', to='core.pecas'),
        ),
        migrations.CreateModel(
            name='OrcamentosServicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_servico', models.CharField(max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.orcamentos')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.servicos')),
            ],
            options={
                'verbose_name': 'Orçamento Serviço',
                'verbose_name_plural': 'Orçamentos Serviços',
            },
        ),
        migrations.AddField(
            model_name='orcamentos',
            name='servicos',
            field=models.ManyToManyField(through='core.OrcamentosServicos', to='core.servicos'),
        ),
    ]
