# Generated by Django 5.0.7 on 2024-07-18 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_orcamentos_pecas_remove_orcamentos_servicos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamentos',
            name='status',
            field=models.IntegerField(choices=[(1, 'DRAFT'), (2, 'EMPROGRESSO'), (3, 'FINALIZADO')], default=1),
        ),
    ]
