# Generated by Django 5.0.7 on 2024-07-19 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_orcamentos_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orcamentospecas',
            name='nome_peca',
        ),
        migrations.RemoveField(
            model_name='orcamentosservicos',
            name='nome_servico',
        ),
    ]
