# Generated by Django 5.0.7 on 2024-07-29 16:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_orcamentospecas_nome_peca_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orcamentospecas',
            name='orcamento',
        ),
        migrations.RemoveField(
            model_name='orcamentosservicos',
            name='orcamento',
        ),
        migrations.RemoveField(
            model_name='orcamentospecas',
            name='peca',
        ),
        migrations.RemoveField(
            model_name='orcamentosservicos',
            name='servico',
        ),
        migrations.CreateModel(
            name='Orcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.IntegerField(choices=[(1, 'Draft'), (2, 'In Progress'), (3, 'Finalized')], default=1)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.clientes')),
            ],
            options={
                'verbose_name': 'Orçamento',
                'verbose_name_plural': 'Orçamentos',
            },
        ),
        migrations.CreateModel(
            name='OrcamentoPeca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pecas', to='core.orcamento')),
                ('peca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pecas')),
            ],
            options={
                'verbose_name': 'Orçamento Peça',
                'verbose_name_plural': 'Orçamentos Peças',
            },
        ),
        migrations.CreateModel(
            name='OrcamentoServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicos', to='core.orcamento')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.servicos')),
            ],
            options={
                'verbose_name': 'Orçamento Serviço',
                'verbose_name_plural': 'Orçamentos Serviços',
            },
        ),
        migrations.DeleteModel(
            name='Orcamentos',
        ),
        migrations.DeleteModel(
            name='OrcamentosPecas',
        ),
        migrations.DeleteModel(
            name='OrcamentosServicos',
        ),
        migrations.AddIndex(
            model_name='orcamento',
            index=models.Index(fields=['cliente'], name='core_orcame_cliente_b13e20_idx'),
        ),
        migrations.AddIndex(
            model_name='orcamento',
            index=models.Index(fields=['status'], name='core_orcame_status_069288_idx'),
        ),
        migrations.AddIndex(
            model_name='orcamentopeca',
            index=models.Index(fields=['orcamento'], name='core_orcame_orcamen_44b3a2_idx'),
        ),
        migrations.AddIndex(
            model_name='orcamentopeca',
            index=models.Index(fields=['peca'], name='core_orcame_peca_id_fbbb4a_idx'),
        ),
        migrations.AddIndex(
            model_name='orcamentoservico',
            index=models.Index(fields=['orcamento'], name='core_orcame_orcamen_10cadf_idx'),
        ),
        migrations.AddIndex(
            model_name='orcamentoservico',
            index=models.Index(fields=['servico'], name='core_orcame_servico_15b9b3_idx'),
        ),
    ]
