# Generated by Django 5.0.7 on 2024-07-29 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_orcamentospecas_orcamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='desconto',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='mao_de_obra',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='preco_sugerido',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orcamentos', to='core.clientes'),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
