# Generated by Django 5.0.7 on 2024-07-29 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_orcamento_desconto_orcamento_mao_de_obra_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
